### ISSUE TITLE
initData方法会闪退

### ISSUE THREAD

**Issue by xinshengBoy** [taixiang/rain_emoji#1]
在initData()方法的getWidth()。调试的时候到这里就直接退出了，应该不能直接这么获取宽高吧

**Comment by taixiang** [comment]
init方法是什么时候触发的，demo里是通过点击触发的，view已经渲染了 可以拿到getWidth
在Activity 的onCreate()方法里触发的话，会报错的

**Comment by xinshengBoy** [comment]
`public RainView(Context context) {
        super(context,null);
    }

    public RainView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs,0);
    }

    public RainView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    private void init() {
        paint = new Paint();
        paint.setAntiAlias(true);//防锯齿
        paint.setFilterBitmap(true);//对位图进行滤波处理
        paint.setDither(true);//防止抖动

        matrix = new Matrix();//矩阵工具类
        random = new Random();//随机工具
        bitmapList = new ArrayList<>();
    }`

这个是调用的地方
`@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_emoje_rain);

        initView();
    }

    private void initView() {
        //// TODO: 2016/12/21 actionbar
        LinearLayout headerLayout = findViewById(R.id.headerLayout);
        Bundle bundle = new Bundle();
        bundle.putBoolean("back", true);
        bundle.putString("leftText", null);
        bundle.putString("title", "表情雨");
        bundle.putBoolean("rightImage", false);
        bundle.putString("rightText", null);
        MyActionBar.actionbar(this,headerLayout,bundle);

        view_emojerain = findViewById(R.id.view_emojerain);
        et_emojeCount = findViewById(R.id.et_emojeCount);
        btn_emojeOne = findViewById(R.id.btn_emojeOne);
        btn_emojeTwo = findViewById(R.id.btn_emojeTwo);

        btn_emojeOne.setOnClickListener(this);
        btn_emojeTwo.setOnClickListener(this);
    }

    @Override
    public void onClick(View view) {
        if (view == btn_emojeOne){
            start(R.mipmap.emoje1);
        }else if (view == btn_emojeTwo){
            start(R.mipmap.emoje2);
        }
    }

    private void start(int imgId){
        String num = et_emojeCount.getText().toString().trim();
        if (num.equals("")){
            LemonHello.getWarningHello("提示","请输入数字");
        }else {
            int count = Integer.parseInt(num);
            view_emojerain.setImgId(imgId, count);
            view_emojerain.start(true);
        }
    }`

跟你的差不多呀，为啥我的就用不了呢，大神指教一下？

**Comment by taixiang** [comment]
```
public RainView(Context context) {
        this(context, null);
    }

    public RainView(Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }
```
构造方法里面传this(....)， 才会走到init方法

**Comment by xinshengBoy** [comment]
可以了，大神就是厉害，哈哈
